<script setup lang="ts">
import { computed, type Component } from 'vue'
import {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  BadgeCheck,
  Banknote,
  BarChart2,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Coins,
  Columns3,
  Compass,
  Copy,
  CreditCard,
  DollarSign,
  DoorOpen,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileDown,
  FileEdit,
  Files,
  FileText,
  FilePlus,
  FileUp,
  Fingerprint,
  Folder,
  Gift,
  Globe,
  GraduationCap,
  Headset,
  Heart,
  IdCard,
  HelpCircle,
  History,
  Home,
  Image,
  Info,
  Landmark,
  Laptop,
  Layers,
  LayoutGrid,
  LayoutList,
  Library,
  Lightbulb,
  Link as LinkIcon,
  List,
  ListChecks,
  Loader,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MapPinOff,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Network,
  Package,
  Palette,
  Paperclip,
  PauseCircle,
  Pencil,
  PieChart,
  Pin,
  Play,
  Plus,
  Presentation,
  Printer,
  QrCode,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldMinus,
  ShieldOff,
  ShoppingCart,
  Sliders,
  SlidersHorizontal,
  Smartphone,
  SquarePen,
  Star,
  StickyNote,
  Sun,
  Tag,
  Tags,
  Target,
  Ticket,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  UsersRound,
  Wallet,
  Wrench,
  X,
  XCircle,
  Phone,
  PhoneOff,
  PhoneMissed,
  Mic,
  MicOff,
  Volume2,
  VolumeX,
  Waves,
  Dumbbell,
  Building2,
  PartyPopper,
  ToyBrick,
  Footprints,
  Activity,
  Trees,
  Cctv,
  Fence,
  Car,
  Zap,
  ArrowUpDown,
  Store,
  Droplet,
  Wifi,
  PawPrint,
  Video,
} from 'lucide-vue-next'

const props = defineProps<{
  name: string
  size?: number
}>()

const iconMap: Record<string, Component> = {
  'book-open': BookOpen,
  'briefcase': Briefcase,
  'compass': Compass,
  'building': Building,
  'building-office': Building,
  'clipboard-list': ClipboardList,
  'home': Home,
  'image': Image,
  'laptop': Laptop,
  'gift': Gift,
  'menu': Menu,
  'package': Package,
  'shield-exclamation': ShieldAlert,
  'shopping-cart': ShoppingCart,
  'tag': Tag,
  'users': Users,
  'users-group': UsersRound,
  'sitemap': Network,
  'clock': Clock,
  'calendar': Calendar,
  'calendar-check': CalendarCheck,
  'calendar-days': CalendarDays,
  'calendar-off': CalendarCheck,
  'clipboard-check': ClipboardCheck,
  'list': List,
  'receipt': Receipt,
  'calculator': Calculator,
  'coins': Coins,
  'file': File,
  'files': Files,
  'chart-bar': BarChart3,
  'chart-line': TrendingUp,
  'chart-pie': PieChart,
  'user-cog': UserCog,
  'shield': Shield,
  'megaphone': Megaphone,
  'settings': Settings,
  'logout': LogOut,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'sun': Sun,
  'moon': Moon,
  'bell': Bell,
  'menu-open': Menu,
  'menu-close': X,
  'x-circle': XCircle,
  'check-circle': CheckCircle,
  'exclamation-circle': AlertCircle,
  'info': Info,
  'info-circle': Info,
  'search': Search,
  'lock': Lock,
  'mail': Mail,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'credit-card': CreditCard,
  'file-text': FileText,
  'shield-check': ShieldCheck,
  'maximize': Maximize2,
  'minimize': Minimize2,
  'plus': Plus,
  'pencil': Pencil,
  'pencil-square': SquarePen,
  'trash': Trash2,
  'check': Check,
  'eye': Eye,
  'eye-off': EyeOff,
  'external-link': ExternalLink,
  'link': LinkIcon,
  'download': Download,
  'upload': Upload,
  'printer': Printer,
  'refresh': RefreshCw,
  'paper-airplane': Send,
  'globe': Globe,
  'camera': Camera,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'document-duplicate': Copy,
  'x-mark': X,
  'x': X,
  'alert-circle': AlertCircle,
  'ticket': Ticket,
  'columns': Columns3,
  'folder': Folder,
  'headset': Headset,
  'map-pin': MapPin,
  'pin': Pin,
  'paperclip': Paperclip,
  'loader': Loader,
  'banknote': Banknote,
  'banknotes': Banknote,
  'wallet': Wallet,
  'wrench': Wrench,
  'refresh-cw': RefreshCw,
  'pie-chart': PieChart,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'circle': Circle,
  'circle-check': CircleCheck,
  'circle-dot': CircleDot,
  'circle-dashed': CircleDashed,
  'circle-x': CircleX,
  'timer': Timer,
  'qr-code': QrCode,
  'smartphone': Smartphone,
  'finger-print': Fingerprint,
  'exclamation-triangle': AlertTriangle,
  'queue-list': ListChecks,
  'list-checks': ListChecks,
  'minus': Minus,
  'crosshair': Target,
  'target': Target,
  'user': User,
  'send': Send,
  'star': Star,
  'history': History,
  'sticky-note': StickyNote,
  'landmark': Landmark,
  'heart': Heart,
  'graduation-cap': GraduationCap,
  'layout-grid': LayoutGrid,
  'presentation': Presentation,
  'check-square': CheckSquare,
  'help-circle': HelpCircle,
  'sliders': Sliders,
  'dots-vertical': MoreVertical,
  // Aliases and additional icons
  'adjustments-horizontal': SlidersHorizontal,
  'alert-triangle': AlertTriangle,
  'archive': Archive,
  'arrow-down-tray': Download,
  'arrow-path': RefreshCw,
  'arrow-right-on-rectangle': LogOut,
  'arrow-top-right-on-square': ExternalLink,
  'arrow-up-tray': Upload,
  'award': Award,
  'badge-check': BadgeCheck,
  'bar-chart-2': BarChart2,
  'books': Library,
  'cash': Banknote,
  'category': LayoutGrid,
  'chat-bubble-left-ellipsis': MessageCircle,
  'chat-bubble-left-right': MessageSquare,
  'clipboard': Clipboard,
  'copy': Copy,
  'currency-dollar': DollarSign,
  'document-arrow-down': FileDown,
  'document-arrow-up': FileUp,
  'document-plus': FilePlus,
  'document': File,
  'document-text': FileText,
  'identification': IdCard,
  'door-exit': DoorOpen,
  'edit': Pencil,
  'ellipsis-horizontal': MoreHorizontal,
  'envelope': Mail,
  'file-edit': FileEdit,
  'layers': Layers,
  'layout-list': LayoutList,
  'lightbulb': Lightbulb,
  'loader-2': Loader2,
  'log-out': LogOut,
  'map-off': MapPinOff,
  'map-pin-off': MapPinOff,
  'message-square': MessageSquare,
  'monitor': Monitor,
  'computer-desktop': Monitor,
  'palette': Palette,
  'pause-circle': PauseCircle,
  'play': Play,
  'video': Video,
  'repeat': Repeat,
  'rotate-ccw': RotateCcw,
  'save': Save,
  'shield-minus': ShieldMinus,
  'shield-off': ShieldOff,
  'tags': Tags,
  'tf-correct': CheckCircle,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'user-check': UserCheck,
  'user-x': UserX,
  // ─── Call & audio ────────────────────────────────────────────────────
  'phone': Phone,
  'phone-off': PhoneOff,
  'phone-missed': PhoneMissed,
  'phone-x-mark': PhoneOff,
  'microphone': Mic,
  'microphone-slash': MicOff,
  'volume': Volume2,
  'volume-off': VolumeX,
  // ─── Amenities ───────────────────────────────────────────────────────
  'waves': Waves,
  'dumbbell': Dumbbell,
  'building-2': Building2,
  'party-popper': PartyPopper,
  'toy-brick': ToyBrick,
  'footprints': Footprints,
  'activity': Activity,
  'trees': Trees,
  'cctv': Cctv,
  'fence': Fence,
  'car': Car,
  'zap': Zap,
  'arrow-up-down': ArrowUpDown,
  'store': Store,
  'droplet': Droplet,
  'wifi': Wifi,
  'paw-print': PawPrint,
}

const iconComponent = computed(() => iconMap[props.name] ?? Info)
const iconSize = computed(() => props.size ?? 20)
</script>

<template>
  <component
    :is="iconComponent"
    :size="iconSize"
    class="inline-block shrink-0"
  />
</template>
